db.engine=supabase

# CORRECCIÓN: URL de conexión JDBC DIRECTA (Usando el puerto 5432 para evitar conflictos con PgBouncer en Java)
supabase.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres?sslmode=require

# Usuario (Formato: usuario.ID_Proyecto)
supabase.user=postgres.uiirgkypwrvgcbncursh

# Tu contraseña
supabase.password=holacomo3stas