
db.engine=supabase

# URL de conexión JDBC (Usando puerto 6543 del Pooler)
supabase.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require

# Usuario (Formato: usuario.ID_Proyecto)
supabase.user=postgres.uiirgkypwrvgcbncursh

# Tu contraseña
supabase.password=holacomo3stas